name: 'healthcare_analytics'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'healthcare_analytics'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  healthcare_analytics:
    # Staging models - materialized as views for speed
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
    
    # Intermediate models - views for flexibility
    intermediate:
      +materialized: view
      +schema: intermediate
      +tags: ["intermediate"]
    
    # Mart models - tables for performance
    marts:
      +materialized: table
      +schema: marts
      +tags: ["marts"]
      # Dimensions
      dim_hospitals:
        +materialized: table
        +schema: marts
      dim_drg_codes:
        +materialized: table
        +schema: marts
      dim_geography:
        +materialized: table
        +schema: marts
      dim_dates:
        +materialized: table
        +schema: marts
      # Facts
      fct_inpatient_charges:
        +materialized: table
        +schema: marts
      fct_readmissions:
        +materialized: table
        +schema: marts
      fct_hospital_summary:
        +materialized: table
        +schema: marts
      fct_state_summary:
        +materialized: table
        +schema: marts

# Configuring snapshots
snapshots:
  healthcare_analytics:
    +target-schema: snapshots
    +strategy: check
    +unique-key: facility_id

# Variables for configuration
vars:
  start_date: '2020-01-01'
  end_date: '2023-12-31'

